export const items = [
    {label: "달", item_name: "튼튼한 달걀 주머니", checked: false},
    {label: "감", item_name: "튼튼한 감자 주머니", checked: false},
    {label: "옥", item_name: "튼튼한 옥수수 주머니", checked: false},
    {label: "밀", item_name: "튼튼한 밀 주머니", checked: false},
    {label: "보", item_name: "튼튼한 보리 주머니", checked: false},
    {label: "양", item_name: "튼튼한 양털 주머니", checked: false},
    {label: "거", item_name: "튼튼한 거미줄 주머니", checked: false},
    {label: "가", item_name: "튼튼한 가는 실뭉치 주머니", checked: false},
    {label: "굵", item_name: "튼튼한 굵은 실뭉치 주머니", checked: false},
    {label: "저", item_name: "튼튼한 저가형 가죽 주머니", checked: false},
    {label: "일", item_name: "튼튼한 일반 가죽 주머니", checked: false},
    {label: "고", item_name: "튼튼한 고급 가죽 주머니", checked: false},
    {label: "최", item_name: "튼튼한 최고급 가죽 주머니", checked: false},
    {label: "저", item_name: "튼튼한 저가형 옷감 주머니", checked: false},
    {label: "일", item_name: "튼튼한 일반 옷감 주머니", checked: false},
    {label: "고", item_name: "튼튼한 고급 옷감 주머니", checked: false},
    {label: "최", item_name: "튼튼한 최고급 옷감 주머니", checked: false},
    {label: "저", item_name: "튼튼한 저가형 실크 주머니", checked: false},
    {label: "일", item_name: "튼튼한 일반 실크 주머니", checked: false},
    {label: "고", item_name: "튼튼한 고급 실크 주머니", checked: false},
    {label: "최", item_name: "튼튼한 최고급 실크 주머니", checked: false},
    {label: "꽃", item_name: "튼튼한 꽃바구니", checked: false},
];

export const sets = [
    "방직",
    "가죽",
    "옷감",
    "실크"
]

export const itemFullname = {
    "튼튼한 달걀 주머니": false,
    "튼튼한 감자 주머니": false,
    "튼튼한 옥수수 주머니": false,
    "튼튼한 밀 주머니": false,
    "튼튼한 보리 주머니": false,
    "튼튼한 양털 주머니": false,
    "튼튼한 거미줄 주머니": false,
    "튼튼한 가는 실뭉치 주머니": false,
    "튼튼한 굵은 실뭉치 주머니": false,
    "튼튼한 저가형 가죽 주머니": false,
    "튼튼한 일반 가죽 주머니": false,
    "튼튼한 고급 가죽 주머니": false,
    "튼튼한 최고급 가죽 주머니": false,
    "튼튼한 저가형 옷감 주머니": false,
    "튼튼한 일반 옷감 주머니": false,
    "튼튼한 고급 옷감 주머니": false,
    "튼튼한 최고급 옷감 주머니": false,
    "튼튼한 저가형 실크 주머니": false,
    "튼튼한 일반 실크 주머니": false,
    "튼튼한 고급 실크 주머니": false,
    "튼튼한 최고급 실크 주머니": false,
    "튼튼한 꽃바구니": false,
}